

STAR = star

# work around SDK's ld not resolving pgplot's transitive system deps on this host
LOAD_EXTRAS = -L/usr/lib/x86_64-linux-gnu -lX11 -lxcb -lXau -lXdmcp -lrt -ldl -lpthread

include $(MESA_DIR)/star/work_standard_makefile
